// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NDE.Data.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NDE.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251121190731_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NDE.Domain.Entities.CodeReviews.CodeReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Closed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Diff")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DiffHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileLink")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("PullRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Suggestion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TokensConsumed")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("VerdictId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PullRequestId");

                    b.ToTable("CodeReviews", (string)null);
                });

            modelBuilder.Entity("NDE.Domain.Entities.CodeReviews.Modification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodeBlock")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CodeReviewId")
                        .HasColumnType("uuid");

                    b.Property<string>("Vector")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CodeReviewId");

                    b.ToTable("CodeModifications", (string)null);
                });

            modelBuilder.Entity("NDE.Domain.Entities.CodeReviews.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CollectionUrl")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("NDE.Domain.Entities.CodeReviews.PullRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("PullRequestId")
                        .HasColumnType("integer");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.Property<int>("TokensConsumed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "PullRequestId")
                        .IsUnique();

                    b.ToTable("PullRequests", (string)null);
                });

            modelBuilder.Entity("NDE.Domain.Entities.CodeReviews.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Repositories", (string)null);
                });

            modelBuilder.Entity("NDE.Domain.Entities.CodeReviews.CodeReview", b =>
                {
                    b.HasOne("NDE.Domain.Entities.CodeReviews.PullRequest", "PullRequest")
                        .WithMany("CodeReviews")
                        .HasForeignKey("PullRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PullRequest");
                });

            modelBuilder.Entity("NDE.Domain.Entities.CodeReviews.Modification", b =>
                {
                    b.HasOne("NDE.Domain.Entities.CodeReviews.CodeReview", "CodeReview")
                        .WithMany("Modifications")
                        .HasForeignKey("CodeReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodeReview");
                });

            modelBuilder.Entity("NDE.Domain.Entities.CodeReviews.PullRequest", b =>
                {
                    b.HasOne("NDE.Domain.Entities.CodeReviews.Repository", "Repository")
                        .WithMany("PullRequests")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("NDE.Domain.Entities.CodeReviews.Repository", b =>
                {
                    b.HasOne("NDE.Domain.Entities.CodeReviews.Project", "Project")
                        .WithMany("Repositories")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("NDE.Domain.Entities.CodeReviews.CodeReview", b =>
                {
                    b.Navigation("Modifications");
                });

            modelBuilder.Entity("NDE.Domain.Entities.CodeReviews.Project", b =>
                {
                    b.Navigation("Repositories");
                });

            modelBuilder.Entity("NDE.Domain.Entities.CodeReviews.PullRequest", b =>
                {
                    b.Navigation("CodeReviews");
                });

            modelBuilder.Entity("NDE.Domain.Entities.CodeReviews.Repository", b =>
                {
                    b.Navigation("PullRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
