// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NDE.Data.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NDE.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NDE.Domain.Entities.CodeReviews.AzureProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ProjectUrl")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("NDE.Domain.Entities.CodeReviews.AzurePullRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "Id")
                        .IsUnique();

                    b.ToTable("PullRequests", (string)null);
                });

            modelBuilder.Entity("NDE.Domain.Entities.CodeReviews.AzureRepository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("RepositoryName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Repositories", (string)null);
                });

            modelBuilder.Entity("NDE.Domain.Entities.CodeReviews.CodeReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Closed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Diff")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DiffHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("PullRequestId")
                        .HasColumnType("integer");

                    b.Property<string>("Suggestion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SummaryReview")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TokensConsumed")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Vector")
                        .HasColumnType("text");

                    b.Property<int>("VerdictId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PullRequestId");

                    b.ToTable("CodeReviews", (string)null);
                });

            modelBuilder.Entity("NDE.Domain.Entities.CodeReviews.AzurePullRequest", b =>
                {
                    b.HasOne("NDE.Domain.Entities.CodeReviews.AzureRepository", "AzureRepository")
                        .WithMany("PullRequests")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AzureRepository");
                });

            modelBuilder.Entity("NDE.Domain.Entities.CodeReviews.AzureRepository", b =>
                {
                    b.HasOne("NDE.Domain.Entities.CodeReviews.AzureProject", "AzureProject")
                        .WithMany("Repositories")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AzureProject");
                });

            modelBuilder.Entity("NDE.Domain.Entities.CodeReviews.CodeReview", b =>
                {
                    b.HasOne("NDE.Domain.Entities.CodeReviews.AzurePullRequest", "AzurePullRequest")
                        .WithMany("CodeReviews")
                        .HasForeignKey("PullRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AzurePullRequest");
                });

            modelBuilder.Entity("NDE.Domain.Entities.CodeReviews.AzureProject", b =>
                {
                    b.Navigation("Repositories");
                });

            modelBuilder.Entity("NDE.Domain.Entities.CodeReviews.AzurePullRequest", b =>
                {
                    b.Navigation("CodeReviews");
                });

            modelBuilder.Entity("NDE.Domain.Entities.CodeReviews.AzureRepository", b =>
                {
                    b.Navigation("PullRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
